export * from './HomePage/HomePage'
export * from 'pages/Product/Product'
export * from 'pages/Contact/Contact'
export * from './Posts/Posts'
export * from './Contact/Contact'
export * from './Repair/Repair'
export * from './RepairHome/RepairHome'
